### ISSUE TITLE
Minifly automatically appends .min in the filename before the extension

### ISSUE THREAD

**Issue by Ryank02** [xxczaki/minifly#1]
For example, I want to minify index.html, and have the minified version overwrite it.
What happens now, is that index.html is untouched, and the minified version of it is called index.min.html.
Maybe it's a good idea to make a parameter to toggle it, or provide a custom name.

Other than that, I really like this tool, makes it really simple to minify all css, html, and js in a folder without using find or specifying the filenames, I use it for deploying to Github Pages.

**Comment by Ryank02** [comment]
Oh and I forgot to say, if this change is okay to you, but you don't have time to do it, then I could give it a shot (I already looked at the code, seems doable for me).

**Comment by Ryank02** [comment]
I'll create a fork first, so I can use it even if you don't want this change.

EDIT:
Already did it, and it seems to be working perfectly.
Here's the repo if you're interested : https://github.com/Ryank02/minifly.
If you want, I can open a PR for those changes, just let me know.

**Comment by xxczaki** [comment]
Hi, 
Glad you like Minifly :smile: It would be great if you could create a PR for that.

**Comment by Ryank02** [comment]
Done! #

**Comment by Ryank02** [comment]
Done! #2
